(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(calendar-date-style 'iso t)
 '(calendar-week-start-day 1 t)
 '(ccls-initialization-options
   '(:diagnostics
     (:onOpen 0 :onSave 0 :onChange -1 :spellChecking :json-false)
     :highlight
     (:largeFileSize 0)))
 '(comint-history-isearch t)
 '(comint-ignore-dups t t)
 '(comint-process-echoes t)
 '(comint-prompt-read-only t)
 '(company-dabbrev-code-ignore-case t)
 '(company-dabbrev-downcase nil)
 '(company-dabbrev-ignore-case t)
 '(company-idle-delay 0)
 '(company-lsp-async t t)
 '(company-lsp-cache-candidates nil t)
 '(company-minimum-prefix-length 2)
 '(company-occurrence-weight-function 'company-occurrence-prefer-any-closest)
 '(company-require-match nil)
 '(company-selection-wrap-around t)
 '(company-tooltip-align-annotations t)
 '(company-tooltip-flip-when-above t)
 '(company-transformers '(company-sort-by-occurrence))
 '(compilation-always-kill t)
 '(compilation-ask-about-save nil)
 '(compilation-auto-jump-to-first-error nil)
 '(compilation-context-lines nil)
 '(compilation-disable-input t)
 '(compilation-scroll-output 'first-error)
 '(counsel-describe-function-preselect 'ivy-function-called-at-point)
 '(counsel-grep-post-action-hook '(recenter))
 '(counsel-mode-override-describe-bindings t)
 '(daemons-always-sudo t t)
 '(dired-auto-revert-buffer t)
 '(dired-du-size-format t t)
 '(dired-du-update-headers t t)
 '(dired-dwim-target t)
 '(dired-hide-details-hide-information-lines nil)
 '(dired-hide-details-hide-symlink-targets nil)
 '(dired-listing-switches "-lFaGh1v --group-directories-first")
 '(dired-ls-F-marks-symlinks t)
 '(dired-omit-verbose nil t)
 '(dired-recursive-copies 'always)
 '(eshell-hist-ignoredups t t)
 '(eshell-history-size 50000 t)
 '(eshell-ls-dired-initial-args '("-h") t)
 '(eshell-ls-exclude-regexp "~\\'" t)
 '(eshell-ls-initial-args "-hA" t)
 '(eshell-smart-space-goes-to-end t t)
 '(eshell-stringify-t nil t)
 '(eshell-where-to-jump 'begin t)
 '(expand-region-autocopy-register "e")
 '(expand-region-fast-keys-enabled nil)
 '(eyebrowse-new-workspace t t)
 '(eyebrowse-switch-back-and-forth t t)
 '(eyebrowse-wrap-around t t)
 '(flymake-diagnostic-at-point-display-diagnostic-function 'flymake-diagnostic-at-point-display-popup t)
 '(flymake-no-changes-timeout nil t)
 '(flymake-start-syntax-check-on-newline nil t)
 '(gdb-many-windows t t)
 '(ibuffer-default-shrink-to-minimum-size t)
 '(ibuffer-saved-filter-groups
   '(("default"
      ("X"
       (mode . exwm-mode))
      ("Dired"
       (mode . dired-mode))
      ("Emacs config"
       (filename . ".emacs.d"))
      ("Org-Mode"
       (mode . org-mode))
      ("Programming"
       (derived-mode . prog-mode))
      ("Magit"
       (name . "magit"))
      ("Processes"
       (process))
      ("Special"
       (or
        (name . "*Messages*")
        (name . "*scratch*")))
      ("Virtual"
       (name . "*")))))
 '(ibuffer-show-empty-filter-groups nil)
 '(imenu-auto-rescan t t)
 '(imenu-auto-rescan-maxout 1048576 t)
 '(isearch-allow-scroll 'unlimited)
 '(isearch-lazy-count t)
 '(isearch-yank-on-move 'shift)
 '(ivy-count-format "")
 '(ivy-height 9)
 '(ivy-rich-path-style 'abbrev)
 '(ivy-rich-switch-buffer-align-virtual-buffer t)
 '(ivy-use-virtual-buffers t)
 '(ivy-virtual-abbreviate 'full)
 '(ivy-wrap t)
 '(js2-skip-preprocessor-directives t t)
 '(json-reformat:indent-width 4 t)
 '(json-reformat:pretty-string\? t t)
 '(lazy-highlight-initial-delay 0)
 '(lsp-auto-guess-root t t)
 '(lsp-before-save-edits nil t)
 '(lsp-enable-indentation nil t)
 '(lsp-enable-on-type-formatting nil t)
 '(lsp-enable-symbol-highlighting nil t)
 '(lsp-pyls-plugins-rope-completion-enabled nil t)
 '(lsp-ui-doc-enable nil t)
 '(lsp-ui-doc-include-signature t t)
 '(lsp-ui-peek-always-show t t)
 '(lsp-ui-sideline-enable nil t)
 '(lsp-ui-sideline-ignore-duplicate t t)
 '(lsp-ui-sideline-show-hover nil t)
 '(lsp-ui-sideline-show-symbol nil t)
 '(magit-diff-arguments
   '("--ignore-space-change" "--ignore-all-space" "--no-ext-diff" "--stat" "--diff-algorithm=histogram") t)
 '(magit-diff-refine-hunk t t)
 '(magit-display-buffer-function 'magit-display-buffer-fullframe-status-v1 t)
 '(magit-process-popup-time 20 t)
 '(magit-refs-show-commit-count 'all t)
 '(multi-term-dedicated-select-after-open-p t t)
 '(multi-term-scroll-show-maximum-output t t)
 '(package-selected-packages
   '(org eclipse-theme log4j-mode iedit beginend general yasnippet which-key wgrep-ag web-mode volatile-highlights visual-fill-column undo-tree symbol-overlay smex smartparens rmsbolt rg realgud rainbow-mode pipenv nasm-mode multiple-cursors multi-term minions magit-gitflow magit lsp-ui company-lsp js2-mode iy-go-to-char ivy-rich ivy-posframe imenu-anywhere hl-todo flymake-diagnostic-at-point eyebrowse expand-region eacl dumb-jump docker disk-usage dired-toggle dired-narrow dired-du daemons cython-mode counsel-etags counsel company comment-dwim-2 cmake-font-lock cmake-mode ccls bug-hunter hydra exec-path-from-shell diminish no-littering ignoramus parchment-theme use-package))
 '(pipenv-projectile-after-switch-function 'pipenv-projectile-after-switch-extended t)
 '(projectile-completion-system 'ivy)
 '(projectile-enable-caching t)
 '(projectile-sort-order 'recentf)
 '(projectile-use-git-grep t)
 '(recentf-auto-cleanup 'never)
 '(recentf-exclude
   '("/usr/share/emacs/.*\\'" "/elpa/.*\\'" "/.ccls-cache/.*\\'" "PKGBUILD" "crontab.*" "/usr/lib/python.*\\'" "/tmp/.*\\'" ignoramus-boring-p))
 '(recentf-max-menu-items 100)
 '(recentf-max-saved-items 500)
 '(rg-hide-command nil t)
 '(rg-ignore-case 'smart t)
 '(show-paren-delay 0)
 '(show-paren-when-point-inside-paren t)
 '(symbol-overlay-displayed-window t)
 '(symbol-overlay-idle-time 0.25)
 '(undo-tree-auto-save-history nil)
 '(undo-tree-enable-undo-in-region nil)
 '(undo-tree-visualizer-diff t)
 '(undo-tree-visualizer-timestamps t)
 '(wdired-allow-to-change-permissions t t)
 '(wdired-create-parent-directories t t)
 '(web-mode-attr-indent-offset 2 t)
 '(web-mode-attr-value-indent-offset 2 t)
 '(web-mode-code-indent-offset 4 t)
 '(web-mode-css-indent-offset 2 t)
 '(web-mode-enable-block-face t t)
 '(web-mode-enable-current-column-highlight t t)
 '(web-mode-enable-current-element-highlight t t)
 '(web-mode-enable-element-content-fontification t t)
 '(web-mode-enable-element-tag-fontification t t)
 '(web-mode-enable-html-entities-fontification t t)
 '(web-mode-enable-inlays t t)
 '(web-mode-enable-part-face t t)
 '(web-mode-enable-sql-detection t t)
 '(web-mode-engines-alist '(("django" . "\\.html\\'")) t)
 '(web-mode-markup-indent-offset 2 t)
 '(web-mode-sql-indent-offset 4 t)
 '(wgrep-auto-save-buffer t t)
 '(which-key-idle-delay 0.75)
 '(which-key-side-window-location 'right)
 '(which-key-sort-order 'which-key-prefix-then-key-order)
 '(whitespace-display-mappings '((tab-mark 9 [187 32 32 32 32 32 32 32])))
 '(whitespace-style '(face tab-mark trailing))
 '(yas-also-auto-indent-first-line t)
 '(yas-triggers-in-field t)
 '(yas-verbosity 1 t)
 '(yas-wrap-around-region t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(symbol-overlay-default-face ((t (:inherit underline)))))
